
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1194:Implement exception constructors.", Justification = "Meh", Scope = "type", Target = "~T:StackExchange.Opserver.Data.IPNet.IPNetParseException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1194:Implement exception constructors.", Justification = "Meh", Scope = "type", Target = "~T:StackExchange.Opserver.Data.DataPullException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Matching SQL fields", Scope = "type", Target = "~T:StackExchange.Opserver.Data.SQL.SQLInstance.WhoIsActiveRow")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "RCS1221:Use pattern matching instead of combination of 'as' operator and null check.", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.SettingsProviders.SettingsProvider.GetCurrentProvider~StackExchange.Opserver.SettingsProviders.SettingsProvider")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0019:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.Dashboard.Providers.WmiDataProvider.WmiNode.GetAllInterfacesAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0019:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.SettingsProviders.SettingsProvider.GetCurrentProvider~StackExchange.Opserver.SettingsProviders.SettingsProvider")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Readability", "RCS1154:Sort enum members.", Justification = "<Pending>", Scope = "type", Target = "~T:StackExchange.Opserver.Data.HAProxy.ProxyServerStatus")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "RCS1146:Use conditional access.", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.Dashboard.DashboardModule.#cctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "RCS1146:Use conditional access.", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.Redis.RedisHost.GetDownstreamHosts(System.Collections.Generic.List{StackExchange.Opserver.Data.Redis.RedisInstance})~System.Collections.Generic.List{StackExchange.Opserver.Data.Redis.RedisHost.ReplicaSummary}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "RCS1146:Use conditional access.", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.PollingEngine.TryRemove(StackExchange.Opserver.Data.PollNode)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "RCS1146:Use conditional access.", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Helpers.FileSizeFormatProvider.Format(System.String,System.Object,System.IFormatProvider)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "RCS1146:Use conditional access.", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.Dashboard.Providers.BosunMetric.GetDenormalized(System.String,System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}})~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0068:Use recommended dispose pattern", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.SQL.SQLInstance.GetConnectionAsync(System.Int32)~System.Threading.Tasks.Task{System.Data.Common.DbConnection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0068:Use recommended dispose pattern", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.Exceptions.ExceptionStore.GetConnectionAsync~System.Threading.Tasks.Task{System.Data.Common.DbConnection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0068:Use recommended dispose pattern", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.Exceptions.ExceptionStore.QueryListAsync``1(System.String,System.String,)~System.Threading.Tasks.Task{System.Collections.Generic.List{``0}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0068:Use recommended dispose pattern", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.Dashboard.Providers.OrionDataProvider.UtilizationQueryAsync``1(System.String,System.String,System.String,System.String,System.Nullable{System.DateTime},System.Nullable{System.DateTime},System.Nullable{System.Int32})~System.Threading.Tasks.Task{System.Collections.Generic.List{``0}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0068:Use recommended dispose pattern", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.Dashboard.Providers.OrionDataProvider.GetNetworkUtilizationAsync(StackExchange.Opserver.Data.Dashboard.Node,System.Nullable{System.DateTime},System.Nullable{System.DateTime},System.Nullable{System.Int32})~System.Threading.Tasks.Task{System.Collections.Generic.List{StackExchange.Opserver.Data.Dashboard.DoubleGraphPoint}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0068:Use recommended dispose pattern", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.Dashboard.Providers.OrionDataProvider.GetVolumePerformanceUtilizationAsync(StackExchange.Opserver.Data.Dashboard.Node,System.Nullable{System.DateTime},System.Nullable{System.DateTime},System.Nullable{System.Int32})~System.Threading.Tasks.Task{System.Collections.Generic.List{StackExchange.Opserver.Data.Dashboard.DoubleGraphPoint}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0068:Use recommended dispose pattern", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.Dashboard.Providers.OrionDataProvider.GetAllNodesAsync~System.Threading.Tasks.Task{System.Collections.Generic.List{StackExchange.Opserver.Data.Dashboard.Node}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0068:Use recommended dispose pattern", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.Dashboard.Providers.OrionDataProvider.GetConnectionAsync~System.Threading.Tasks.Task{System.Data.Common.DbConnection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0068:Use recommended dispose pattern", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.Exceptions.ExceptionStore.QueryListAsync``1(System.String,System.String,)~System.Threading.Tasks.Task{System.Collections.Generic.List{``0}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0068:Use recommended dispose pattern", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Helpers.Connection.GetOpenAsync(System.String,System.Nullable{System.Int32})~System.Threading.Tasks.Task{System.Data.Common.DbConnection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0068:Use recommended dispose pattern", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.Exceptions.ExceptionStore.GetErrorAsync(System.String,System.Guid)~System.Threading.Tasks.Task{StackExchange.Exceptional.Error}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0068:Use recommended dispose pattern", Justification = "<Pending>", Scope = "member", Target = "~M:StackExchange.Opserver.Data.SQL.SQLInstance.RemovePlanAsync(System.Byte[])~System.Threading.Tasks.Task{System.Int32}")]

