<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Opserver</RootNamespace>
    <AssemblyName>Opserver.Core</AssemblyName>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Enums.NET" />
    <PackageReference Include="Jil" />
    <PackageReference Include="Microsoft.Data.SqlClient"/>
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Net.Http.Headers" />
    <PackageReference Include="MiniProfiler.Shared" />
    <PackageReference Include="Sigil" />
    <PackageReference Include="StackExchange.Exceptional.Shared" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="StackExchange.Utils.Http" />
    <PackageReference Include="System.DirectoryServices" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.Runtime.Caching" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Data\SQL\QueryPlans\ShowPlanXML.cs" SubType="Code" />
    <Compile Update="Data\SQL\QueryPlans\ShowPlanXML.generated.cs" SubType="Code" />
  </ItemGroup>
</Project>