name: Date Based Version
description: Generates a version based on todays date and the github actions run number.  Exposes this version as an output variable.
outputs:
  version:
    description: "Generated Date Based Version"
    value: ${{ steps.generate-version.outputs.version }}

runs:
  using: composite
  steps:
  - name: Generate Version
    id: generate-version
    shell: bash
    run: |
      set -euo pipefail
      github_run_number=${{ github.run_number }}
      github_ref=${{ github.ref }}
      build_number=$(($github_run_number % 65535))

      date=$(date +%Y.%-m.%-d)

      version="${date}.${build_number}"
      is_pr=0
      echo $github_ref | grep "^refs\/pull\/" && is_pr=1

      if [ $is_pr -eq 1 ]
      then
        version="${version}-pr"
      fi

      echo "Version: $version"
      echo "version=$version" >> $GITHUB_OUTPUT
