name: Docker Image CI

on:
  push:
    paths:
    - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Opserver Docker Image
      run: |
        docker build --tag opserver/opserver-ci:latest --target web .